
networks:
  survey_net:
    driver: bridge
  db_net:
    driver: bridge

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: survey_user
      POSTGRES_PASSWORD: byLKPwMrfG48xVT71YCK
      POSTGRES_DB: survey_db
    volumes:
      - ./volumes/db_data:/var/lib/postgresql/data/
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_net
    expose:
      - "5432"  # Makes the port accessible only to connected containers

  survey_app:
    build: ./survey_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://survey_user:byLKPwMrfG48xVT71YCK@db/survey_db
    networks:
      - survey_net
      - db_net
    ports:
      - "5002:5000"

  csv_export:
    build: ./csv_export
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://survey_user:byLKPwMrfG48xVT71YCK@db/survey_db
    volumes:
      - csv_data:/app/csv_files
    networks:
      - survey_net
      - db_net
    ports:
      - "5001:5001"


volumes:
  db_data:
  csv_data:
